// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnEHIFmMFY4H44jjlUm-si_mcAoFQ38Uc',
    appId: '1:21712256481:web:41c1d4b600fe3e637326a0',
    messagingSenderId: '21712256481',
    projectId: 'tourismapp-e188e',
    authDomain: 'tourismapp-e188e.firebaseapp.com',
    storageBucket: 'tourismapp-e188e.appspot.com',
    measurementId: 'G-P3T35NMVEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkgKRmyM0C_Ze9FbuD1LOgXWPmsc4ECIk',
    appId: '1:21712256481:android:a893ea66fe20fcdb7326a0',
    messagingSenderId: '21712256481',
    projectId: 'tourismapp-e188e',
    storageBucket: 'tourismapp-e188e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYnj9LZx12taE3_RqBcKl9sNuq_NJ39M8',
    appId: '1:21712256481:ios:cef2883aa9c0bcce7326a0',
    messagingSenderId: '21712256481',
    projectId: 'tourismapp-e188e',
    storageBucket: 'tourismapp-e188e.appspot.com',
    iosBundleId: 'com.example.tourismApp',
  );
}
